[manifest]
version = "1.0.0"
dump_lua = true
priority = -9

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
        shake_amt = (G.SETTINGS.reduced_motion and 0 or 1)*G.SETTINGS.screenshake/100*3
'''
position = "at"
payload = '''
shake_amt = (G.JS_MENU and 0 or 1)*(G.SETTINGS.reduced_motion and 0 or 1)*G.SETTINGS.screenshake/100*3
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "engine/ui.lua"
pattern = 'Node.update(self, dt)'
position = "before"
payload = '''
if self.config.JS_drag then
        local cont = G.CONTROLLER
        if cont.is_cursor_down and cont.cursor_down.target == self then
                self:click(true)
                self.last_clicked = 0
        end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "engine/ui.lua"
pattern = 'function UIElement:click()'
position = "at"
payload = '''
function UIElement:click(no_audio)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "engine/ui.lua"
pattern = '''play_sound('button', 1, 0.3)'''
position = "at"
payload = '''
if not no_audio then play_sound('button', 1, 0.3) end
'''
match_indent = true
