[manifest]
version = "1.0.0"
dump_lua = true
priority = -9

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
        shake_amt = (G.SETTINGS.reduced_motion and 0 or 1)*G.SETTINGS.screenshake/100*3
'''
position = "at"
payload = '''
shake_amt = (G.JS_MENU and 0 or 1)*(G.SETTINGS.reduced_motion and 0 or 1)*G.SETTINGS.screenshake/100*3
'''
match_indent = true





